[theme]
base = "light"
primaryColor = "#5A2D81"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F9F7FC"
textColor = "#333333"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false